package handlers

import "testing"

// normalizeSlashCommand сворачивает обёртку слэш-команды из JSONL в человекочитаемый вид
// и СКРЫВАЕТ служебные блоки. Проверяем все формы, что встречаются в ленте claude.
func TestNormalizeSlashCommand(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "обычный текст не трогаем",
			in:   "просто сообщение пользователя",
			want: "просто сообщение пользователя",
		},
		{
			name: "command-name + args + stdout → команда и результат",
			in:   "<command-name>/clear</command-name>\n<command-args>all</command-args>\n<local-command-stdout>готово</local-command-stdout>",
			want: "/clear all\nготово",
		},
		{
			name: "только command-name (без слеша) → добавляем слеш",
			in:   "<command-name>compact</command-name>",
			want: "/compact",
		},
		{
			name: "только stdout",
			in:   "<local-command-stdout>результат команды</local-command-stdout>",
			want: "результат команды",
		},
		{
			name: "ОДИНОЧНЫЙ caveat (служебная инструкция модели) → скрываем",
			in:   "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>",
			want: "",
		},
		{
			name: "caveat + команда → caveat выкидываем, команду оставляем",
			in:   "<local-command-caveat>Caveat: …</local-command-caveat>\n<command-name>/status</command-name>",
			want: "/status",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := normalizeSlashCommand(c.in); got != c.want {
				t.Errorf("normalizeSlashCommand(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

// workspaceSlug должен СОВПАДАТЬ с тем, как claude называет папку проекта в ~/.claude/projects
// (claude сохраняет регистр буквы диска, неалфанумерику → "-"). Регресс на ошибочный
// «строчим диск» фикс, который ломал резолв (бэкенд искал c--…, а claude писал C--…).
func TestWorkspaceSlug(t *testing.T) {
	cases := map[string]string{
		`C:\Users\evgen\nebulide-ws`:        "C--Users-evgen-nebulide-ws",
		"C:/Users/evgen/nebulide-ws":        "C--Users-evgen-nebulide-ws",
		"/home/nebulide/workspace":          "-home-nebulide-workspace",
		`c:\Users\evgen\.projects\Clauder`:  "c--Users-evgen--projects-Clauder",
	}
	for in, want := range cases {
		if got := workspaceSlug(in); got != want {
			t.Errorf("workspaceSlug(%q) = %q, want %q", in, got, want)
		}
	}
}
